                                                             -- Create database healthcare_mng_CaseStudy;
use healthcare_mng_CaseStudy;

-- how many patients are registered from each address
select address, count(patient_id) from patients group by address;

-- payment status distribution
select payment_status, count(bill_id) from billing group by payment_status;

select * from patients;
 select * from appointments where appointment_date >= 
 (select max(appointment_date) from appointments)- interval 7 day order by appointment_date desc;
 
-- find min cost, max cost, avg cost of the treatment
select min(cost), max(cost), avg(cost) from treatments;

-- What is the age distribution of patients
select patient_id, first_name, gender, timestampdiff(year, date_of_birth, curdate()) as age from patients;

-- make age distribution 
-- 18-35 = Adult
-- 36-55 = Mature
-- 56+ = Old
with Age as (Select patient_id,timestampdiff(year, date_of_birth, curdate()) as age1 from patients)
select 
case when age1 <18 then "Minors" else(
	case when age1 between 18 and 35 then 'Adult' else 
		(case when age1 between 36 and 55 then 'Mature' else "Old_age" end)         /* Nested case statement*/
	end )
end as age_group, count(patient_id) as Patient_count from age group by age_group order by Patient_count desc ;

-- OR 

create view Age3 as Select *, timestampdiff(year, date_of_birth, curdate()) as age1 from patients;
select case 
			when age3.age1 < 18 then 'Minors'
			when age3.age1 between 18 and 35 then "Adults"
            when age3.age1 between 36 and 55 then "Mature"
			else 'Old_age' 
    end as Age_group, count(patient_id) as patient_count from age3 
    group by age_group order by patient_count desc;         /* I have used View to not write again & again timestamp query, 
    we can use multiple when statement in single case statement instead of nested case statement */
    
    
-- Which email domain commonly used by petients
select * from patients;
select substring(email, locate('@', email)) as email_domain, count(patient_id) from patients   /* locate finds first posotion of @*/
 group by email_domain order by  count(patient_id) desc;         

-- which month had highr patient registration
select monthname(registration_date) as months , count(patient_id) as patient_count from patients group by months order by patient_count desc limit 1;

-- which medical specialisation are mostly in demand based on appointment volume 
select d.Specialization as high_demand_speczn, count(a.appointment_id) as Demand from appointments a   join doctors d on a.doctor_id=d.doctor_id
group by high_demand_speczn;

-- critical specialization supported by senior experienced doctor and junior experienced doctor 
-- < 15 = Junior
-- >15 = Senior
select specialization, count(doctor_id) as doctor_count, 
sum(case when years_experience < 15 then 1 else 0 end )as 'Junior',
sum(case when years_experience >= 15 then 1 else 0 end) as 'Senior' from doctors group by specialization;

-- make a table/ master data ...appointments with patient details and doctors specialization
select a.*, concat(p.first_name,' ', p.last_name) as patient_name , concat(d.first_name,' ', d.last_name) AS doctor_name, d.specialization from appointments a 
left join patients p on a.patient_id=p.patient_id
left join doctors d on d.doctor_id=a.doctor_id;

-- which doctors are overloaded and which doctors have available capacity based on appointment value 
select concat(d.first_name, ' ',d.last_name) as doctor_name, d.specialization,count(a.appointment_id) as appointment_count from doctors d 
inner join appointments a on d.doctor_id=a.doctor_id group by concat(d.first_name, ' ',d.last_name),d.specialization 
order by appointment_count asc ;

-- build master data where we can see the patient entire journney from appointment > treatments > billing
select p.*, a.*,t.*,b.* from patients p inner join appointments a on p.patient_id=a.patient_id
left join treatments t on t.appointment_id=a.appointment_id
left join billing b on b.treatment_id=b.treatment_id;

-- what is total revenue generated by company 
select round(sum(amount),2) as Total_revenue from billing where payment_status ="Paid";

-- which patients contribute the most revenue
select concat(p.first_name,' ',p.last_name) as patient_name, round(sum(amount),3) as Total_revenue
 from patients p inner join billing b on p.patient_id=b.patient_id where b.payment_status="Paid"
 group by concat(p.first_name,' ',p.last_name) order by Total_revenue desc ;
 
 -- RFM segmentatiom
 -- recency , frequency, monetary
 use healthcare_mng_casestudy ;
 select max(cost) from treatments;
 -- create RFM metrices	per patients using :- last visit, total visit, paid spend
 -- label "champions", 'loyal high value', 'risk'
 with rfm as (
 select p.patient_id, concat(p.first_name, p.last_name) as patient_name,
 max(a.appointment_date) last_visit, count(distinct a.appointment_id) as frequency,
 round(coalesce (sum(case when b.payment_status = 'Paid' then b.amount end),0),2) as monetary from patients p left join appointments a
 on p.patient_id = a.patient_id left join billing b 
 on p.patient_id=b.patient_id group by p.patient_id, patient_name
 ),
 scored as (
 select *, datediff(curdate(), last_visit) as recency_days,
 ntile(4) over (order by datediff(curdate(), last_visit) asc) as r_score , -- lower receny better
 ntile(4) over (order by frequency desc) as f_score,
 ntile(4) over (order by monetary desc) as m_score from rfm)
 select patient_id, patient_name, recency_days, frequency,monetary,
 r_score, f_score, m_score, concat(r_score,f_score,m_score) as rfm_code,
 case when r_score >=3 and f_score >=3 and m_score>=3 then "Champions"
 when f_score >=3 and m_score >=3 then "Loyal High Value"
 when r_score <=2 and f_score <=2 then "High risk/ Inactive"
 when f_score >=3 then "Frequent visitors"
 when m_score >=3 then "High spenders"
 else "Regular" end as Segment from scored order by monetary desc, frequency desc;

-- outlier detection
-- are there treatments with unusually high cost that require review 
select treatment_id, treatment_type, cost from treatments where cost > (select avg(cost) +2*stddev(cost) from treatments);

-- rank doctors by total appointment
select concat(d.first_name, d.last_name) as doctor_name, 
d.specialization, 
count(a.appointment_id) 
from doctors d 
left join appointments a 
on d.doctor_id=a.doctor_id 
group by doctor_name, specialization 
order by count(a.appointment_id) desc;

-- rank patients by total spending (VIP patients)
select concat(p.first_name, p.last_name) as patient_name, round(coalesce(sum(b.amount),0),2) as total_spending, 
rank() over(order by  round(coalesce(sum(b.amount),0),2) desc) as spending_rank from patients p 
left join billing b on p.patient_id=b.patient_id where b.payment_status ="Paid" group by patient_name;

-- select treatment by frequency
select treatment_type, count(treatment_id) as treatment_count, 
rank() over (order by count(treatment_id) desc) as frequency_rank from treatments group by treatment_type;

-- count the number of patient from patients table
select count(distinct patient_id) from patients;

-- count rows in appointments table
select count(*) from appointments;

-- are there appointment status that indicate patient disagreement  risk ?
select status, count(*) as appointment_count from appointments group by status;
--  no show + cancelled > scheduled + completed = high patient diaengagement risk

-- which patients are repeatedly missing appointment and may need inetrvention
-- appoitment>3 and no -show rate > 40
with patient_summary as  (select p.patient_id, concat(p.first_name, p.last_name) as patient_name,
count(appointment_id) as total_appointment,
sum(case when a.status = "No-show" then 1 else 0 end) as no_show_count,
round(sum(case when a.status = "No-show" then 1 else 0 end)* 100 / count(appointment_id),2) as no_show_rate,
count(appointment_id)- sum(case when a.status = "No-show" then 1 else 0 end) as meet_appointment
from patients p join  appointments a on p.patient_id=a.patient_id group by p.patient_id, patient_name)
select * from patient_summary order by no_show_count desc;

-- rank doctors by total appointments
select concat(d.first_name, d.last_name) as doctor_name, count(a.appointment_id) as total_appointment,
rank() over (order by count(appointment_id) desc) as doctors_rank 
 from doctors d join appointments a on d.doctor_id=a.doctor_id 
group by  doctor_name;

-- rank patient by total spending
select p.patient_id, p.first_name ,sum(b.amount) as total_spent, rank() over (order by sum(b.amount) desc) as spending_rank
from patients p join billing b on p.patient_id=b.patient_id where b.payment_status ='Paid'group by p.patient_id, p.first_name;

-- monthly appointment trend
	select year(appointment_date) as year, month(appointment_date) as month,
	count(appointment_id) as total_appointments from appointments group by year, month order by year, month;
-- appoinrments by day of week
select dayname(appointment_date) as day_of_week, count(appointment_id) as total_appointment
from appointments group by day_of_week;

-- monthly revenue trend
select year(bill_date) as year,month(bill_date) as month, round(sum(amount),2) as total_revenue from billing where payment_status = "Paid"
group by year,month order by year, month;

-- appointment sequence per patient
select patient_id, appointment_id, appointment_date, 
row_number() over (partition by patient_id order by appointment_date) as visit_number
from appointments;

-- what is gap between patient visit
select patient_id, appointment_id, appointment_date, 
datediff(appointment_date,lag(appointment_date) over (partition by patient_id order by appointment_date)) as gap_between_visit
from appointments;
